version: '3.8'
services:
  app:
    build: ./app
    restart: always
    environment:
      DB_URL: mysql+pymysql://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}/${DB_NAME}
      FLASK_ENV: production
    volumes:
      - ./app:/app
    depends_on:
      - database
    links:
      - database
    networks:
      - flask
  
  database:
    build: ./db
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - flask


  nginx:
    build: ./nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app/static:/app/static
    depends_on:
      - app
    networks:
      - flask

volumes:
  db-data:
  # static-data:

networks:
  flask: