# Use the official Nginx image as the base image
FROM nginx:stable-alpine3.17-slim

# Copy the custom Nginx configuration
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Expose the Nginx port
EXPOSE 80

